---
- name: check from devices operationnal state if desirated vlans are presents
  hosts: test
  connection: local
  gather_facts: no
  vars_files:
  - "vlans.yml"
  
  tasks:

  - name: check vlan
    junos_command:
      provider: "{{  credentials }}"
      commands:
       - show vlans {{item.name}}
      waitfor:
       - "result[0]['junos-rpc']['vlan-information']['vlan']['vlan-name'] eq {{item.name }} "
    with_items: "{{ vlans }}"
