---
- name: Create directories for each host
  hosts: AMS-EX4200
  connection: local
  gather_facts: no
  tasks:
    - name: remove host build temp directory
      file: path=configs/{{inventory_hostname}}.conf state=absent
    - name: create host build temp directory
      file: path=configs/ state=directory
