---
 - name: Retrieve configuration from junos devices
   hosts: AMS-EX4200
   roles:
    - Juniper.junos
   connection: local
   gather_facts: no
   
   tasks:
   - name: include vars
     include_vars: "{{playbook_dir}}/vars.yml"
     
   - name: Retrieve configuration from junos devices
     junos_get_config:
      host={{ inventory_hostname }}
      user={{ USERNAME }}
      passwd={{ DEVICE_PASSWORD }}
      dest={{playbook_dir}}/configs/{{ inventory_hostname }}.conf
      format=text
      logfile={{playbook_dir}}/get_config.log
      filter=interfaces
