---
  - name: Load Configs From Jinja2 Templates
    hosts: sws
    roles:
     - Juniper.junos
    connection: local
    gather_facts: no
    vars:
      - junos_jinja_template: "load-conf-from-template/template-dns-servers.j2"
      - path: "load-conf-from-template/junos_configs" #the directory must already exist
    vars_files:
      - "load-conf-from-template/variables-dns-servers.yml"
 
    tasks:
 
    - name: Retrieve information from devices running Junos OS
      junos_get_facts:
        host={{ inventory_hostname }}
        user={{ ADMUSER }}
        passwd={{ ADMPASS }}
      register: junos
 
 
    - name: Create Junos configurations from Jinja2
      template: src={{ junos_jinja_template }} dest="{{ path }}/{{ junos.facts.hostname }}.conf" #the destination directory must already exist
 
 
    - name: Install Junos configuration template
      junos_install_config:
        host={{ inventory_hostname }}
        user={{ADMUSER}}
        passwd={{ADMPASS}}
        #replace=yes
        file="{{ path }}/{{ junos.facts.hostname }}.conf"
        diffs_file="load-conf-from-template/{{ junos.facts.hostname }}.log"
