---
- name: Change configuration using junos_config module
  hosts: AMS-test
  connection: local
  gather_facts: no
  vars_files:
  - "vlans.yml"
  
  tasks:

  - name: create vlans
    junos_config:
      lines:
        - "set vlans {{ item.name }} vlan-id {{ item.id }}"
      comment: "create vlans from Ansible"
      provider: "{{ credentials }}"
    with_items: "{{ vlans }}"

  - name: check vlan
    junos_command:
      provider: "{{  credentials }}"
      commands:
       - show vlans {{item.name}}
      waitfor:
       - "result[0].l2ng-l2ald-vlan-instance-information.l2ng-l2ald-vlan-instance-group.l2ng-l2rtb-name eq {{item.name}} "
      retries: 10
      interval: 1
     with_items: "{{ vlans }}"
