---
  - name: Load Configs From Jinja2 Templates
    hosts: Chris EX4200 test
    roles:
     - Juniper.junos
    connection: local
    gather_facts: no
    vars:
      - junos_jinja_template: "dns-servers.j2"
      - path: "junos_configs"
    vars_files:
      - "dns-servers.yml"
 
    tasks:
 
    - name: this task simply ensures this directory exists 
      file: path={{ path }} state=directory
      
    - name: Retrieve information from devices running Junos OS
      junos_get_facts:
        host={{ inventory_hostname }}
        user={{ ADMUSER }}
        passwd={{ ADMPASS }}
      register: junos
      
    - name: Create Junos configurations from Jinja2
      template: src={{ junos_jinja_template }} dest="{{ path }}/{{ junos.facts.hostname }}.set" #the destination directory must already exist
      
    - name: Install Junos configuration template
      junos_install_config:
        host={{ inventory_hostname }}
        user={{ADMUSER}}
        passwd={{ADMPASS}}
        file="{{ path }}/{{ junos.facts.hostname }}.set"
        diffs_file="{{ junos.facts.hostname }}.log"
        
    - name: remove host build temp directory
      file: path=configs/{{inventory_hostname}}.conf state=absent
      
    - name: create host build temp directory
      file: path=configs/ state=directory
      
    - name: Retrieve configuration from devices running Junos
      junos_get_config:
        host={{ inventory_hostname }}
        user={{ADMUSER}}
        passwd={{ADMPASS}}
        dest=configs/{{ inventory_hostname }}.conf
        format=text
        logfile=get_config.log
        filter=name-server
    
  
