 - name: pass cli
   hosts: Chris EX4200 test
   roles:
    - Juniper.junos
   connection: local
   gather_facts: no
   tasks:
    - name: junos cli
      junos_cli:
       host={{ inventory_hostname }}
       user=pytraining
       passwd=Poclab123
       cli="show configuration vlans"
       logfile=cli.log
       dest={{ inventory_hostname }}.txt
      register: output 
 
    #- name: Print output
    #  debug: msg="{{ output.stdout }}" 
    
    - name: set fact vlans_conf 
      set_fact: vlans_conf="{{ output }}"
      
    - name: set fact vlans_conf_lines 
      set_fact: vlans_conf_lines="{{ vlans_conf.split('\n') }}"

    #- name: set vlan list 
    #  set_fact: vlans_list="{{ output.stdout | regex.findall('vlan-id (.+)') }}"

    #- name: Print some facts
    #  debug: msg="{{ vlans_list }}"
